(
    <div className="[font-synthesis:none] flex flex-col w-360 py-10 px-16 gap-2 border-t border-t-solid border-t-[#FFFFFF0F] antialiased">
      <div className="text-[#FFFFFF33] font-['DM_Sans',system-ui,sans-serif] text-xs/4">
        Symphony Token Intelligence · Generated by token-report.sh · Data from ~/Library/Logs/symphony/
      </div>
      <div className="text-[#FFFFFF26] font-['DM_Sans',system-ui,sans-serif] text-xs/4">
        Retention: 90 days · Next report: 2026-03-25 06:00 ET · Inflection attribution uses "coincides with" language — hypotheses, not conclusions.
      </div>
    </div>
  )
