/**
 * Section 9: Report Footer
 * Converted from design reference ReportFooter.jsx.
 * Rebuilt with v5 inline styles (SYMPH-205).
 */
export default function ReportFooter() {
  return (
    <footer
      style={{
        fontFamily: "var(--font-body)",
        fontSize: "var(--font-size-caption)",
        color: "var(--color-text-secondary)",
        lineHeight: "var(--line-height-body)",
        marginTop: "var(--spacing-section)",
        textAlign: "center",
        padding: "var(--spacing-group) 0",
        borderTop: "var(--border-width) solid var(--border-color)",
      }}
    >
      Symphony Token Report &middot; Self-contained &middot; Generated by
      token-report.mjs &middot; SYMPH-131
    </footer>
  );
}
