import type { FooterProps } from "./types.ts";

/**
 * Section 5: Footer
 * Page footer with branding and generation metadata.
 * Font families: Inter (per structure.md)
 */
export default function Footer({ brand, year }: FooterProps) {
  return (
    <footer
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "16px 32px",
        borderTop: "1px solid #E2E8F0",
        width: "100%",
        maxWidth: "1440px",
        height: "80px",
        boxSizing: "border-box",
      }}
    >
      <span
        style={{
          fontFamily: "Inter, sans-serif",
          fontSize: "12px",
          color: "#64748B",
        }}
      >
        {brand} © {year}
      </span>
      <span
        style={{
          fontFamily: "Inter, sans-serif",
          fontSize: "12px",
          color: "#94A3B8",
        }}
      >
        Generated by export-design skill
      </span>
    </footer>
  );
}
